In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("data_cleaning sample.csv")

## cleaning data

In [14]:
df1= df[df["Name"].notnull()].sort_values(by='Age',ascending=False).drop_duplicates().fillna(int(df['Age'].mean()))

In [15]:
df1

      Name   Age         City Gender              Email   Join Date
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

## Export the cleaned dataset

In [17]:
df1.to_csv("Clean_data.csv",index=False)

In [19]:
data = pd.read_csv("Clean_data.csv")
data

      Name   Age         City Gender              Email   Join Date
0      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
1    Alice  25.0     New York      F  alice@example.com  01-05-2021
2    David  22.0       Mumbai      M  david@example.com  12-11-2019
3  Charlie  25.0        Delhi      M    charlie@example  20-07-2021