In [1]:
import pandas as pd
df = pd.read_csv("data_cleaning sample.csv")

In [2]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [3]:
filtered_rows = df[(df['Name'].notnull())]
filtered_rows

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [7]:
df1= filtered_rows
df2= df1.sort_values(by="Age",ascending=False)
df2

      Name   Age         City Gender              Email   Join Date
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

## final dataset with ascending and not NaN value

In [11]:
final_dataset=df2.drop_duplicates().fillna(0)

In [12]:
final_dataset

      Name   Age         City Gender              Email   Join Date
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021